### ISSUE TITLE
modification requirements for mypage(Todo)

### ISSUE THREAD

**Issue by mkson417** [swsnu/swppfall2022-team2#22]
Error occurs in `mypage.views.mypage_submit` if invalid form of input has sent(e.g. 'abc' in _age_ field)

- need to verify form type at frontend

Other requirements are ...

- Fetching some information from `mypage.model.UserInfo` and fill forms in _mypage_ with its stored value by default

- Implements for `MyTimeTable.tsx` and `MyManner.tsx` and according backends

- Demanding some informations when registering(at `SignUp.tsx`)

**Comment by 0114kek** [comment]
추가로 
1. 변경 버튼을 눌렀을때 정상적으로 수행됐는지 alert와 비슷한것도 필요하고
2. 일반적인 화면 크기에서 왼쪽의 온도 부분과 오른쪽의 정보 설정하는 부분 사이에 빈 공간이 너무 많은 문제도 있습니다
